### ISSUE TITLE
Morph Ball occaisionally gets "stuck"

### ISSUE THREAD

**Issue by TerminusEst13** [TerminusEst13/ducking-avenger#1]
Every now and then, a player will (seemingly randomly) morph into a light green Morph Ball.
In this, the player is stuck in Morph Ball form and simply cannot unmorph outside of death.

A quick check of printinv shows that the unmorph/remorph ACS is working and the items are being taken away/given, but the player is not actually being unmorphed.

**Comment by DaZombieKiller** [comment]
As I understand it, when you are morphed, you merely control another actor, you aren't really "morphed". I would imagine that PrintInv shows the correct inventory items because it's checking for them on the actual player, rather than the morphed class.

I'm not entirely sure of this however, so it shall require further investigation.

**Comment by TerminusEst13** [comment]
This seems to have mostly fixed itself, which is incredibly worrying.

On the one hand, I'm really glad that I don't have to deal with it anymore.
On the other hand, code isn't sentient and can't magically decide to start working, so I'm worried this is going to pop up again nastier than ever.

Closed...for now.
